# Generated by Django 3.2.4 on 2021-07-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cl', models.TextField()),
                ('correo', models.TextField()),
                ('asunto', models.TextField()),
                ('sugerencia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('nombre_mec', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=20)),
                ('fecha', models.TextField()),
                ('materiales', models.TextField()),
                ('categoria', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='atenciones')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webRayoMakween.mecanico')),
            ],
        ),
    ]
