# Generated by Django 3.2.4 on 2021-07-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayoMakween', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentario',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='trabajos',
            old_name='categoria',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='id',
        ),
        migrations.AddField(
            model_name='trabajos',
            name='codigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajos',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajos',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
