# Generated by Django 3.2.4 on 2021-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayoMakween', '0002_auto_20210709_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico',
            name='nombre_mec',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='diagnostico',
            field=models.CharField(max_length=50),
        ),
    ]
