# Generated by Django 3.1.2 on 2021-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webRayoMakween', '0003_auto_20210709_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='catego'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
